version: 2.1 b{build}
skip_tags: true
image:
  - Visual Studio 2019
  - Ubuntu
configuration: Release
for:
-
  matrix:
    only:
      - image: Ubuntu
  install:
    - sudo apt-get update
    - sudo apt-get --assume-yes install gcc-multilib g++-multilib gcc-4.9-multilib g++-4.9-multilib p7zip-full
  build_script:
    - git submodule update --init --recursive
    - cp vcpkg_triplet/x86-linux-sm.cmake vcpkg/triplets
    - cd vcpkg
    - ./bootstrap-vcpkg.sh    
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 10
    - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 10
    - ./vcpkg install libarchive --triplet x86-linux-sm
    - cd ..
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-linux-sm
    - cd ..
    - cmake --build build --config Release --parallel
  after_build:
    - sh: 7z a amxxarch-linux.zip ./build/amxxarch_amxx_i386.so
  artifacts:
    - path: amxxarch-linux.zip
      name: amxxarch-linux
  deploy:
    - provider: GitHub
      description: nightly
      auth_token:
        secure: QDEGzc09i3TjexbQdbxWkOIfYdIkoFZDOyG4e+uFywRQQ5JDuyO3eFPW9dAlf+5u
      artifact: amxxarch-linux
      on:
        branch: master
      prerelease: true
-

  matrix:
    only:
       - image: Visual Studio 2019
  build_script:
    - git submodule update --init --recursive
    - cp vcpkg_triplet/x86-windows-sm.cmake vcpkg/triplets
    - cd vcpkg
    - .\bootstrap-vcpkg.bat
    - .\vcpkg install libarchive --triplet x86-windows-sm
    - cd ..
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-sm  -A Win32
    - cd ..
    - cmake --build build --config Release --parallel
  after_build:
    - cmd: 7z a amxxarch-win32.zip ./build/Release/amxxarch_amxx.dll
  artifacts:
    - path: amxxarch-server-win32.zip
      name: amxxarch-server-win32
  deploy:
    - provider: GitHub
      description: nightly
      auth_token:
        secure: QDEGzc09i3TjexbQdbxWkOIfYdIkoFZDOyG4e+uFywRQQ5JDuyO3eFPW9dAlf+5u
      artifact: amxxarch-win32
      on:
        branch: master
      prerelease: true